### ISSUE TITLE
Note as context

### ISSUE THREAD

**Issue by epka** [logancyang/obsidian-copilot#7] opened 2023-05-06 19:41 UTC
I may have misunderstood something, but how Note context is intended to work? With note open, selecting 'Note as context' -button only promotes error notification 'Please check your API key and credentials'

**Comment by Hopsakee** [comment] 2023-05-10 19:19
Same here.

**Comment by logancyang** [comment] 2023-05-10 21:17
@epka @Hopsakee Sorry for the confusion. The issue is that I currently have this "Please check your API key and credentials" error message for all OpenAI-related errors. The reason for your error is most likely that your note is too long and it exceeded the token limit. In the meantime, you could confirm that by opening the console and checking the real error message.

I will soon add better error messages for OpenAI API failures (recently I've seen cases where the GPT-4 API is simply down and returning 500). I'm also adding unlimited context length which is a much more exciting update. Please stay tuned!

**Comment by logancyang** [comment] 2023-05-10 23:40
Just made a new release 1.2.1 with better OpenAI error messages like this, please let me know if it helps. 

<img width="883" alt="Screenshot 2023-05-10 at 4 27 36 PM" src="https://github.com/logancyang/obsidian-copilot/assets/4860545/f69c400d-9d88-48e8-8664-1d29e67d9909">

**Comment by logancyang** [comment] 2023-05-12 20:29
I opened another https://github.com/logancyang/obsidian-copilot/issues/12 to track the next feature that will enable longer notes as context. Please feel free to chime in there with ideas. Closing this one for now as I added clearer OpenAI error messages.

**Closed by logancyang** 2023-05-12 20:29 UTC
Labels: bug

**Comment by Hopsakee** [comment] 2023-05-15 18:55
I know this item is closed.
I just wanted to let you know I do indeed get the "token limit exceeded" error after the update. Thanks, that is more helpfull. 

Still have an issue though. If I estimate the tokens for the note using Text Generator plugin I get approximately 2900 tokens. I increased max tokens in the Copilot plugin settings to 3500. But still no luck. To make it even more remarkable, I can summarize using Text Generator plugin. 

But I assume this will be solved for Copilot with issue #12 so you can keep this issue #7 closed as far as I am concerend. But I thought I should give some feedback, because I commented on this issue.

**Comment by logancyang** [comment] 2023-05-15 19:30
@Hopsakee Thanks for the feedback! Yes I'm aware of this and was experimenting with it. The issue sometimes is that the prompts I use to wrap the API call themselves are taking up tokens, which leaves the room for note content much smaller. I decided not to implement a hack to avoid this, but to go directly toward langchain. Will make some changes soon and post over there https://github.com/logancyang/obsidian-copilot/issues/12
