### ISSUE TITLE
langchain error module_not_found

### ISSUE THREAD

**Issue by pohall63** [logancyang/obsidian-copilot#115] opened 2023-07-20 07:22 UTC
I am on a mac book pro M1. 

<img width="838" alt="image" src="https://github.com/logancyang/obsidian-copilot/assets/133255283/e29b0a72-3016-4627-9991-0b96002021db">

Any suggetions?

**Comment by woodae99** [comment] 2023-07-20 08:38
Same (similar) issue here. My error is "LangChain error: model_not_found

**Comment by logancyang** [comment] 2023-07-20 21:35
@pohall63 @woodae99 I will need more information about how to reproduce to be helpful.

What model were you using? What settings, model selection, mode selection do you have?

`model not found` is mostly because you don't have access to that API.

**Comment by woodae99** [comment] 2023-07-21 08:21
@logancyang ...Thanks for your reply - you're right, I read the sticky but thought I had access to the GPT 4 API, turns out I don't! Thanks for the awesome plugin and sorry for the error!

**Comment by pohall63** [comment] 2023-07-21 09:24
@logancyang Sorry Logan, I assued having CHAT GPT 4 access was 32K but now I am also aware of this. Are you considering making the plugin available for GPT 4?

**Comment by logancyang** [comment] 2023-07-23 21:03
@pohall63 Not sure if you mean OpenAI plugins, I don't have a plan to enable OpenAI plugins yet. My goal is to make this work locally eventually without the need to call any API over the network.

Closing this one.

**Closed by logancyang** 2023-07-23 21:03 UTC
