### ISSUE TITLE
Ollama service is still offline in version 2.6.2

### ISSUE THREAD

**Issue by jsrdcht** [logancyang/obsidian-copilot#598] opened 2024-09-05 13:08 UTC
**Describe how to reproduce**
choose Ollama, then set the URL as **http://my_URL**

**Screenshots**
![image](https://github.com/user-attachments/assets/e4086292-74c2-4a2a-9b5f-146921070a53)

![image](https://github.com/user-attachments/assets/c1723f77-3090-4bb8-b8bb-c022b4562aac)

I got this in the debug console
```
plugin:copilot:88285 Model request failed: Error: Connection error.
    plugin:copilot:88285 Model request failed: Error: Connection error.
    at OpenAI.makeRequest (plugin:copilot:75393:13)
    at async eval (plugin:copilot:80814:21)
    at async RetryOperation.eval [as _fn] (plugin:copilot:4237:19)
```

**Additional context**
I'm using plugin Companion and Smart Second Brain too, and they are working well, so I guess my Ollama service is working.

**Comment by logancyang** [comment] 2024-09-05 14:20
Hmm, the relevant error got cutoff at the top. That means the model failed the switching.

Can you make sure your update to 2.6.2, turn the plugin off and on, reset your settings?

I can't reproduce this. Just tried adding some nonsense and it didn't trigger the error at the top. Anyways it's helpful if you show that error in full.

<img width="451" alt="SCR-20240905-gzub" src="https://github.com/user-attachments/assets/2d21df17-ea81-4f59-9848-5a73184137d0">
<img width="495" alt="SCR-20240905-gzvv" src="https://github.com/user-attachments/assets/ef465af3-daa5-47cd-9e50-b95c22b1e3b5">

Anyone else seeing this?

**Comment by jsrdcht** [comment] 2024-09-05 14:44
> Hmm, the relevant error got cutoff at the top. That means the model failed the switching.
> 
> Can you make sure your update to 2.6.2, turn the plugin off and on, reset your settings?
> 
> I can't reproduce this. Just tried adding some nonsense and it didn't trigger the error at the top. Anyways it's helpful if you show that error in full.
> 
> <img alt="SCR-20240905-gzub" width="451" src="https://private-user-images.githubusercontent.com/4860545/364815747-2d21df17-ea81-4f59-9848-5a73184137d0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU1NDc2NjgsIm5iZiI6MTcyNTU0NzM2OCwicGF0aCI6Ii80ODYwNTQ1LzM2NDgxNTc0Ny0yZDIxZGYxNy1lYTgxLTRmNTktOTg0OC01YTczMTg0MTM3ZDAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkwNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MDVUMTQ0MjQ4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MWI4ZWNjMWUzMGI5NTBiNjQ2ODFmNjJlMmE5ZjI1ODVmMTY3NTBiOGI4ZDExZjQ3OWZiN2VhN2RiMTEyNmE0YSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.ZbnhKOCF3IuL7OHTvM-uumcQyXSbObLMIry-XaOsLM8"> <img alt="SCR-20240905-gzvv" width="495" src="https://private-user-images.githubusercontent.com/4860545/364815754-ef465af3-daa5-47cd-9e50-b95c22b1e3b5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU1NDc2NjgsIm5iZiI6MTcyNTU0NzM2OCwicGF0aCI6Ii80ODYwNTQ1LzM2NDgxNTc1NC1lZjQ2NWFmMy1kYWE1LTQ3Y2QtOWU1MC1iOTVjMjJiMWUzYjUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkwNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MDVUMTQ0MjQ4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OWU3YTlmNzYyYzJjNTU3YWYwZGI1MjRhNDg4MmM1NDJiY2JkMDhlMjI3ZjgyMGY1ZWQwZjY5ODFhYjQ2NTQzNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.MXesZIdmc5WaHow4sxLRZvNiqYHBsczqSLnaw_hJt10">
> Anyone else seeing this?

My ollama URL is http://ollama.knowspace.xyz, can you test based on it?

**Comment by logancyang** [comment] 2024-09-05 14:56
@jsrdcht yeah sure. Whatever URL shouldn't cause that error at the top in 2.6.2. So what you are seeing is weird

<img width="578" alt="SCR-20240905-hmrh" src="https://github.com/user-attachments/assets/7a2b2ca6-51d4-412e-83c1-373d73c56323">
<img width="729" alt="SCR-20240905-hmux" src="https://github.com/user-attachments/assets/3451ccfb-da34-4f64-9e30-c04a8a886d86">

**Comment by jsrdcht** [comment] 2024-09-05 15:12
I can set the model too, but when i start to chat, the error will be raised.
![image](https://github.com/user-attachments/assets/21393747-87ae-4a17-9159-e1b81ac76b8b)

**Comment by logancyang** [comment] 2024-09-05 16:22
i do not have access to your server log. If this is your own deployment you can check your server log to further debug. Or just try different base URL, with or without `/v1` etc.

**Comment by logancyang** [comment] 2024-09-05 19:12
Do you have CORS on for this model?

**Comment by jsrdcht** [comment] 2024-09-05 19:17
> Do you have CORS on for this model?

If I don't select CROS, an error will occur.
```
VM300 plugin:copilot:88285 Model request failed: Error: 404 404 page not found
    at APIError3.generate (VM300 plugin:copilot:74581:14)
    at OpenAI.makeStatusError (VM300 plugin:copilot:75363:22)
    at OpenAI.makeRequest (VM300 plugin:copilot:75407:24)
    at async eval (VM300 plugin:copilot:80814:21)
    at async RetryOperation.eval [as _fn] (VM300 plugin:copilot:4237:19)
```

After I select CROS, then the error turns to 
```
Model request failed: Error: Connection error.
    at OpenAI.makeRequest (plugin:copilot:75393:13)
    at async eval (plugin:copilot:80814:21)
    at async RetryOperation.eval [as _fn] (plugin:copilot:4237:19)
```

I just tried the old version of the obsidian-copilot plugin, and it worked very smoothly.

**Comment by logancyang** [comment] 2024-09-05 19:29
@jsrdcht When you say it works in the old version of the plugin, did you turn on local proxy? 

CORS error looks like this though, your 404 doesn't look like a CORS issue
<img width="280" alt="SCR-20240905-lfep" src="https://github.com/user-attachments/assets/fecc68b9-7cb9-4f52-a50d-5c106c82ea09">

**Comment by include** [comment] 2024-09-05 22:19
I am having the same problem.
Note that I have other remote clients (private) using this ollama server on which I had to add the OLLAMA_ORIGINS="*" flag. (private network)

**Comment by jsrdcht** [comment] 2024-09-06 02:07
> @jsrdcht When you say it works in the old version of the plugin, did you turn on local proxy? I'll need the details of how it worked to understand your situation better.
> 
> CORS error looks like this though, your 404 doesn't look like a CORS issue <img alt="SCR-20240905-lfep" width="280" src="https://private-user-images.githubusercontent.com/4860545/364918998-fecc68b9-7cb9-4f52-a50d-5c106c82ea09.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU1ODc2MjcsIm5iZiI6MTcyNTU4NzMyNywicGF0aCI6Ii80ODYwNTQ1LzM2NDkxODk5OC1mZWNjNjhiOS03Y2I5LTRmNTItYTUwZC01YzEwNmM4MmVhMDkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkwNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MDZUMDE0ODQ3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZjRkZWEzOTMwMDVjNzA2Zjc1Y2RiMTMwNzgxM2Q4YmM3Yzc3YzQyNjZkN2JiZjBjMDBhY2MwOGYzZjFjNzQ2NiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.1Z8al8VbFP0NGxqQyUc-WzI7W7BJj4rwZotCo31gbBs">

I test the version 2.5.2 on a windows PC and it works with or without the proxy. Then I test the version 2.6.2 on a MACBOOK with CORS off and proxy on, and I got
```
Model request failed: Error: Connection error.
    at OpenAI.makeRequest (plugin:copilot:75393:13)
    at async eval (plugin:copilot:80814:21)
    at async RetryOperation.eval [as _fn] (plugin:copilot:4237:19)
```
After that, I turn off the proxy (CORS is not selected), then I got some errors like this, a series of errors ended with a mistake similar to the one encountered when enabling the proxy.
![image](https://github.com/user-attachments/assets/5253f9f6-eaa3-4825-949e-b42a11db19cc)

And the Ollama server log looks like this
```
Sep 06 09:53:41 ct-ESC4000A-E10 ollama[13646]: [GIN] 2024/09/06 - 09:53:41 | 404 |        5.43µs |  211.20.157.175 | POST     "/chat/completions"
Sep 06 09:53:43 ct-ESC4000A-E10 ollama[13646]: [GIN] 2024/09/06 - 09:53:43 | 404 |        5.34µs |  211.20.157.175 | POST     "/chat/completions"
Sep 06 09:53:48 ct-ESC4000A-E10 ollama[13646]: [GIN] 2024/09/06 - 09:53:48 | 404 |       6.592µs |  211.20.157.175 | POST     "/chat/completions"
Sep 06 09:53:49 ct-ESC4000A-E10 ollama[13646]: [GIN] 2024/09/06 - 09:53:49 | 404 |       4.469µs |  211.20.157.175 | POST     "/chat/completions"
Sep 06 09:53:50 ct-ESC4000A-E10 ollama[13646]: [GIN] 2024/09/06 - 09:53:50 | 404 |       4.509µs |  211.20.157.175 | POST     "/chat/completions"
Sep 06 09:55:24 ct-ESC4000A-E10 ollama[13646]: [GIN] 2024/09/06 - 09:55:24 | 204 |      16.381µs |  211.20.157.175 | OPTIONS  "/chat/completions"
Sep 06 09:55:24 ct-ESC4000A-E10 ollama[13646]: [GIN] 2024/09/06 - 09:55:24 | 404 |      16.482µs |  211.20.157.175 | POST     "/chat/completions"
Sep 06 09:56:17 ct-ESC4000A-E10 ollama[13646]: [GIN] 2024/09/06 - 09:56:17 | 404 |      16.191µs |  211.20.157.175 | POST     "/chat/completions"
Sep 06 09:56:30 ct-ESC4000A-E10 ollama[13646]: [GIN] 2024/09/06 - 09:56:30 | 403 |       5.701µs |  122.96.144.130 | OPTIONS  "/chat/completions"
Sep 06 09:56:31 ct-ESC4000A-E10 ollama[13646]: [GIN] 2024/09/06 - 09:56:31 | 403 |       6.131µs |  122.96.144.130 | OPTIONS  "/chat/completions"
Sep 06 09:56:32 ct-ESC4000A-E10 ollama[13646]: [GIN] 2024/09/06 - 09:56:32 | 403 |       4.529µs |  122.96.144.130 | OPTIONS  "/chat/completions"
Sep 06 09:56:34 ct-ESC4000A-E10 ollama[13646]: [GIN] 2024/09/06 - 09:56:34 | 403 |       6.061µs |  122.96.144.130 | OPTIONS  "/chat/completions"
Sep 06 09:56:35 ct-ESC4000A-E10 ollama[13646]: [GIN] 2024/09/06 - 09:56:35 | 403 |       7.033µs |  122.96.144.130 | OPTIONS  "/chat/completions"
Sep 06 09:56:39 ct-ESC4000A-E10 ollama[13646]: [GIN] 2024/09/06 - 09:56:39 | 403 |       6.433µs |  122.96.144.130 | OPTIONS  "/chat/completions"
Sep 06 09:56:42 ct-ESC4000A-E10 ollama[13646]: [GIN] 2024/09/06 - 09:56:42 | 403 |        5.05µs |  122.96.144.130 | OPTIONS  "/chat/completions"
Sep 06 09:56:44 ct-ESC4000A-E10 ollama[13646]: [GIN] 2024/09/06 - 09:56:44 | 403 |        5.04µs |  122.96.144.130 | OPTIONS  "/chat/completions"
Sep 06 09:56:45 ct-ESC4000A-E10 ollama[13646]: [GIN] 2024/09/06 - 09:56:45 | 403 |       6.523µs |  122.96.144.130 | OPTIONS  "/chat/completions"
Sep 06 09:56:50 ct-ESC4000A-E10 ollama[13646]: [GIN] 2024/09/06 - 09:56:50 | 403 |       6.322µs |  122.96.144.130 | OPTIONS  "/chat/completions"
Sep 06 09:56:51 ct-ESC4000A-E10 ollama[13646]: [GIN] 2024/09/06 - 09:56:51 | 403 |       6.132µs |  122.96.144.130 | OPTIONS  "/chat/completions"
Sep 06 09:56:52 ct-ESC4000A-E10 ollama[13646]: [GIN] 2024/09/06 - 09:56:52 | 403 |       6.783µs |  122.96.144.130 | OPTIONS  "/chat/completions"
```

Then I turned on the CORS and keep the proxy off, I got
```
plugin:copilot:88285 Model request failed: Error: Connection error.
    at OpenAI.makeRequest (plugin:copilot:75393:13)
    at async eval (plugin:copilot:80814:21)
    at async RetryOperation.eval [as _fn] (plugin:copilot:4237:19)
```
The Ollama server also has some request
```
Sep 06 10:04:08 ct-ESC4000A-E10 ollama[13646]: [GIN] 2024/09/06 - 10:04:08 | 404 |      49.154µs |  122.96.144.130 | POST     "/chat/completions"
Sep 06 10:04:09 ct-ESC4000A-E10 ollama[13646]: [GIN] 2024/09/06 - 10:04:09 | 404 |       4.829µs |  122.96.144.130 | POST     "/chat/completions"
Sep 06 10:04:10 ct-ESC4000A-E10 ollama[13646]: [GIN] 2024/09/06 - 10:04:10 | 404 |       6.523µs |  122.96.144.130 | POST     "/chat/completions"
Sep 06 10:04:12 ct-ESC4000A-E10 ollama[13646]: [GIN] 2024/09/06 - 10:04:12 | 404 |       9.478µs |  122.96.144.130 | POST     "/chat/completions"
Sep 06 10:04:13 ct-ESC4000A-E10 ollama[13646]: [GIN] 2024/09/06 - 10:04:13 | 404 |       5.411µs |  122.96.144.130 | POST     "/chat/completions"
Sep 06 10:04:14 ct-ESC4000A-E10 ollama[13646]: [GIN] 2024/09/06 - 10:04:14 | 404 |       6.543µs |  122.96.144.130 | POST     "/chat/completions"
Sep 06 10:04:19 ct-ESC4000A-E10 ollama[13646]: [GIN] 2024/09/06 - 10:04:19 | 404 |       7.715µs |  122.96.144.130 | POST     "/chat/completions"
Sep 06 10:04:20 ct-ESC4000A-E10 ollama[13646]: [GIN] 2024/09/06 - 10:04:20 | 404 |       6.513µs |  122.96.144.130 | POST     "/chat/completions"
Sep 06 10:04:21 ct-ESC4000A-E10 ollama[13646]: [GIN] 2024/09/06 - 10:04:21 | 404 |       5.901µs |  122.96.144.130 | POST     "/chat/completions"
Sep 06 10:04:28 ct-ESC4000A-E10 ollama[13646]: [GIN] 2024/09/06 - 10:04:28 | 404 |       7.935µs |  122.96.144.130 | POST     "/chat/completions"
Sep 06 10:04:29 ct-ESC4000A-E10 ollama[13646]: [GIN] 2024/09/06 - 10:04:29 | 404 |       3.788µs |  122.96.144.130 | POST     "/chat/completions"
Sep 06 10:04:31 ct-ESC4000A-E10 ollama[13646]: [GIN] 2024/09/06 - 10:04:31 | 404 |         4.8µs |  122.96.144.130 | POST     "/chat/completions"
lines 61-100/100 (END)
```

**Comment by jsrdcht** [comment] 2024-09-06 02:25
> I am having the same problem. Note that I have other remote clients (private) using this ollama server on which I had to add the OLLAMA_ORIGINS="*" flag. (private network)

I have added Environment="OLLAMA_ORIGINS=app://obsidian.md*" to the environment variables, and it works well in other clients.

**Comment by logancyang** [comment] 2024-09-06 02:55
@jsrdcht What do you mean by "CORS off proxy on in 2.6.2"? There's no local proxy in 2.6.2.

**Comment by jsrdcht** [comment] 2024-09-06 04:12
> @jsrdcht What do you mean by "CORS off proxy on in 2.6.2"? There's no local proxy in 2.6.2.
> 
> 403 is unauthorized, possibly wrong API key, where did you put in the API key?
> 
> 404 is no model found for Ollama, what model name did you use?

The `proxy` I mentioned means proxy like `Clash`. It does not refer to the proxy features provided by Obsidian or its plugins.
I did not fill in any API.
I use qwen2:7b, as the picture illustrates,
![image](https://github.com/user-attachments/assets/2184beb4-30b4-40a9-9751-b37175d309cc)

The model is availiable, it can be used in plugin Smart Second Brain
![image](https://github.com/user-attachments/assets/2f6288d1-1220-4cc1-8a92-3a15dc725f1d)

**Comment by logancyang** [comment] 2024-09-06 04:28
@jsrdcht ok let me try one last thing, will check back.

**Comment by logancyang** [comment] 2024-09-06 06:01
@jsrdcht I tested against your url and it's working. Pls test the new version 2.6.3. If it works you might consider redact your URL in this issue to avoid others abusing your endpoint.

**Comment by logancyang** [comment] 2024-09-06 06:20
Ah sht... this damn ChatOllama client doesn't conform with the same format as others. It has `model` instead of `modelName` on their client. So many fking differences... Missed one again. Correct model name will be in the next release then, sorry about that.

**Comment by jsrdcht** [comment] 2024-09-06 08:58
> @jsrdcht I tested against your url and it's working. Pls test the new version 2.6.3. If it works you might consider redacting your URL in this issue to avoid others abusing your endpoint.

I just tried version 2.6.3, and this issue has been resolved. Thank you for your work!

**Closed** 2024-09-06 09:05 UTC
Labels: bug
