### ISSUE TITLE
LocalAI: Error with Drop-In OpenAI API Replacement

### ISSUE THREAD

**Issue by musixela** [logancyang/obsidian-copilot#134] opened 2023-08-25 18:41 UTC
So I am currently using LM Studio to run my LocalAI Server rather than the command-line based structure you propose for install. It would be nice to see expansion of support for this implementation of LocalAI. If you look at the screenshot below, you will find the full information I have currently, but the error in the server log is:

"[2023-08-25 14:28:34.725] [INFO] Received OPTIONS request to /v1/chat/completions with body: {}
[2023-08-25 14:28:34.727] [ERROR] 'messages' field is required."

I would like to note that BMO's implementation currently works, so there may be something useful in their repo. Thanks in advance for reading. You're awesome for working on this project!

<img width="1389" alt="Screenshot 2023-08-25 at 2 31 30 PM" src="https://github.com/logancyang/obsidian-copilot/assets/7844079/731d08ba-85c0-4fda-acc7-39c1b5068682">

**Comment by Sokole1** [comment] 2023-08-25 19:56
Hi @musixela if you aren't using LocalAI (https://github.com/go-skynet/LocalAI) to serve the OpenAI drop-in replacement, try keeping the chat selection to gpt-3-turbo (not LocalAI). When the OpenAI Proxy Base URL is set, it will send the request to that URL instead of the ChatGPT API endpoint. See #113. This feature was added before the LocalAI support, so perhaps the instructions could be improved.

If this doesn't work, can you send screenshots of your Obsidian Copilot settings?

**Comment by musixela** [comment] 2023-08-26 05:03
That isn't the issue. The issue is that the 'messages' field isn't posting to the Local server. I did try it the way you recommended, but I'm getting the same error. I found the console in Obsidian, so I can see that it is a CORS error. If I find a workaround, I'll post an update.

<img width="549" alt="Screenshot 2023-08-26 at 1 01 50 AM" src="https://github.com/logancyang/obsidian-copilot/assets/7844079/69be40ee-5b7b-4809-b204-9997d4800dfe">

**Comment by Sokole1** [comment] 2023-08-26 17:54
Hi @musixela I see, I downloaded LM Studio and ran into the same issue. LM Studio is quite nice, it runs the models really well on my mac. The issue is that Langchain uses `fetch` and not Obsidian's `requestUrl` method. If LM Studio enables CORS, then the issue should be fixed. However, if they don't, then adding back a proxy server would work https://github.com/logancyang/obsidian-copilot/pull/120. 

I should also mention that LM Studio currently doesn't support other endpoints such as /embeddings so QA: Active Note won't work, a different embedding provider should be used. If you want to use LocalAI for example to provide embeddings, then a setting to override the URL endpoint specifically for embeddings would need to be added.

**Comment by musixela** [comment] 2023-08-26 19:54
Thanks @Sokole1

Yeah LM Studio is just getting started, but I think it shows a lot of promise and the active development is happening so fast. I'll add your comment to the thread on the Discord. Once yagil finishes the GGUF compatibility, he'll probably look into it.

**Closed** 2024-01-25 00:11 UTC
