### ISSUE TITLE
[BUG] The copilot-index-hash.json crashes obsidian on Android tablet

### ISSUE THREAD

**Issue by ALE-ARME** [logancyang/obsidian-copilot#739] opened 2024-10-23 13:19 UTC
- [x] Disable all other plugins besides Copilot **(required)**
- [ ] Screenshot of note + Copilot chat pane + dev console added **(required)**

I can't screenshot because the app crashes. I don't know how to open the dev console from android (I have a BT keyboard, so I could use the shortcuts), but anyway it crashes and I don't know if I can see the console log from a previous session

Copilot version: 2.7.0

(Bug report without the above will be closed)

**Describe how to reproduce**
I have embedded my notes with Google's text-embedding-004 (I wanted to use the multilingual version but apparently it can't find it) from windows 10. From the pc and Android phone everything works, but if I open obsidian on the tablet it crashes after setting the model (gemini 1.5 pro, which is my default one). I've found out that the cause of the crash is the copilot-index-has.json, cause the app crashes only when it is present and the plugin enabled (if I move it to another folder of the tablet outside the vault, the app doesn't crash)

**Expected behavior**
To not crash on my tablet when the file is present

**Additional context**
The .json is 36.19MB

**Comment by logancyang** [comment] 2024-10-23 19:59
That's interesting, you mentioned it works on an Android phone but not an Android tablet. I wonder what's the variable there.

**Comment by upnix** [comment] 2024-10-23 23:08
I believe I'm experiencing the same issue on an Android 13 phone (Fairphone 4), Copilot 2.7.0.

I can install, enable, and configure Copilot and Obsidian restarts just fine. But as soon as copilot does the vault embedding (creating the `copilot-index-<hash>.json` file) Obsidian will crash on start-up.

This all worked on the same device with Copilot 2.6...something.. I'm happy to try to debug, but will need some direction.

**Comment by logancyang** [comment] 2024-10-23 23:19
@upnix was it crashing as soon as indexing starts, during indexing, or after it completes?

**Comment by upnix** [comment] 2024-10-23 23:28
I'm using Syncthing. My computer does the indexing and the .json gets copied over to my phone via Syncthing.

For whatever it's worth, I'm also only using a local model. I'll make a new vault on my phone and try to index some documents there.

**Comment by upnix** [comment] 2024-10-23 23:40
New vault, mobile-only, I can index, then search, using OpenAI text-embedding-3-small.

@ALE-ARME how big is your .json file that causes Obsidian to crash? What embedding model are you using?

For my crashing vault the .json is 64MB and I'm using Ollama+nomic-embed-text

**Comment by ALE-ARME** [comment] 2024-10-24 07:01
> New vault, mobile-only, I can index, then search, using OpenAI text-embedding-3-small.
> 
> @ALE-ARME how big is your .json file that causes Obsidian to crash? What embedding model are you using?
> 
> For my crashing vault the .json is 64MB and I'm using Ollama+nomic-embed-text

36.19MB
text-embedding-004 from google

**Comment by upnix** [comment] 2024-10-26 01:23
There's a chance this is related to the size of the .json file.

Strictly on my phone, with a new vault, I indexed 741 files using Google's 'text-embedding-004' model. It counts all the way up to 741, then Obsidian crashes without me doing anything. But it looks like the .json file gets corrupted. I see that the file exists (only 4MB however), and if I start Obsidian again it'll start indexing all 741 files again - and then crash again.

To reiterate, with many few files indexed I had no problem.

@logancyang - any other ideas on how I could narrow this down further?

**Comment by upnix** [comment] 2024-10-26 13:40
I hooked my phone up to my computer and catch the Obsidian log messages being thrown by/to `logcat`. It looks like Obsidian is running out of memory. I've attached the entire logcat dump for Obsidian in case that's of any use (I know it's only an Obsidian plugin we're interested in), but here's why I think we're running out of memory:
```
2024-10-26 07:30:46.483 20047-20047 md.obsidian             md.obsidian                          I  Starting a blocking GC Alloc
2024-10-26 07:30:46.493 20047-20047 md.obsidian             md.obsidian                          I  Alloc concurrent copying GC freed 16KB AllocSpace bytes, 0(0B) LOS objects, 10% free, 203MB/227MB, paused 45us,25us total 10.538ms
2024-10-26 07:30:46.494 20047-20047 md.obsidian             md.obsidian                          W  Throwing OutOfMemoryError "Failed to allocate a 150994952 byte allocation with 25165824 free bytes and 52MB until OOM, target footprint 238468592, growth limit 268435456" (VmSize 33433788 kB)
2024-10-26 07:30:46.494 20047-20047 AndroidRuntime          md.obsidian                          D  Shutting down VM
2024-10-26 07:30:46.499 20047-20047 AndroidRuntime          md.obsidian                          E  FATAL EXCEPTION: main (Ask Gemini)
                                                                                                    Process: md.obsidian, PID: 20047
                                                                                                    java.lang.OutOfMemoryError: Failed to allocate a 150994952 byte allocation with 25165824 free bytes and 52MB until OOM, target footprint 238468592, growth limit 268435456
                                                                                                    	at java.lang.StringUTF16.newBytesFor(StringUTF16.java:50)
                                                                                                    	at java.lang.AbstractStringBuilder.inflate(AbstractStringBuilder.java:233)
                                                                                                    	at java.lang.AbstractStringBuilder.appendChars(AbstractStringBuilder.java:1706)
                                                                                                    	at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:639)
                                                                                                    	at java.lang.StringBuilder.append(StringBuilder.java:226)
                                                                                                    	at org.json.JSONTokener.nextString(JSONTokener.java:233)
                                                                                                    	at org.json.JSONTokener.nextValue(JSONTokener.java:111)
                                                                                                    	at org.json.JSONTokener.readObject(JSONTokener.java:403)
                                                                                                    	at org.json.JSONTokener.nextValue(JSONTokener.java:104)
                                                                                                    	at org.json.JSONTokener.readObject(JSONTokener.java:403)
                                                                                                    	at org.json.JSONTokener.nextValue(JSONTokener.java:104)
                                                                                                    	at org.json.JSONObject.<init>(JSONObject.java:168)
                                                                                                    	at org.json.JSONObject.<init>(JSONObject.java:185)
                                                                                                    	at com.getcapacitor.JSObject.<init>(JSObject.java:22)
                                                                                                    	at com.getcapacitor.MessageHandler.postMessage(MessageHandler.java:54)
                                                                                                    	at com.getcapacitor.MessageHandler.lambda$new$0(MessageHandler.java:29)
                                                                                                    	at com.getcapacitor.MessageHandler.$r8$lambda$b6hmE4Rac4043AR046V2PyojtWU(Unknown Source:0)
                                                                                                    	at com.getcapacitor.MessageHandler$$ExternalSyntheticLambda0.onPostMessage(Unknown Source:7)
                                                                                                    	at androidx.webkit.internal.WebMessageListenerAdapter.onPostMessage(WebMessageListenerAdapter.java:55)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at org.chromium.support_lib_boundary.util.BoundaryInterfaceReflectionUtil$InvocationHandlerWithDelegateGetter.invoke(BoundaryInterfaceReflectionUtil.java:162)
                                                                                                    	at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
                                                                                                    	at $Proxy4.onPostMessage(Unknown Source)
                                                                                                    	at WV.pX.run(chromium-TrichromeWebViewGoogle6432.aab-stable-666810033:101)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:942)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:201)
                                                                                                    	at android.os.Looper.loop(Looper.java:288)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7932)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:942)
```

This happens after all the content is done being indexed. There are many, many, many lines of `A resource failed to call close.` Prior to that, but, my feeling is that most of those were logged before the indexing even started.
[Obsidian_Copilot_Crash.txt](https://github.com/user-attachments/files/17530783/Obsidian_Copilot_Crash.txt)

**Comment by upnix** [comment] 2024-10-26 16:23
Discovered the Obsidian plugin 'Logstravaganza.' Installed that, turned on Copilot debugging, and ended up with something that looks a bit like what I have below. I truncated *a lot*, but the start and the end are included with '...' in rows where I cut out a bunch. Hopefully this is helpful to someone - it doesn't contain the smoking gun I was hoping for.

| Timestamp                | Originator                           | Level | Message                                                                                                                                                                                                                               |
| ------------------------ | ------------------------------------ | ----- | ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| 2024-10-26T13:46:15.554Z | plugin:logstravaganza                | info  | \[Logstravaganza] Proxy set up (v2.1.1)                                                                                                                                                                                               |
| 2024-10-26T13:47:07.740Z | plugin:copilot:143036:15             | error | \["Error reloading plugin:",{}]                                                                                                                                                                                                       |
| 2024-10-26T13:47:17.224Z | plugin:logstravaganza                | info  | \[Logstravaganza] Proxy set up (v2.1.1)                                                                                                                                                                                               |
| 2024-10-26T13:47:18.495Z | at http://localhost/app.js:1:3166481 | error | \[{"code":"ENOENT"}]                                                                                                                                                                                                                  |
| 2024-10-26T13:47:18.508Z | at http://localhost/app.js:1:3166481 | error | \[{"code":"ENOENT"}]                                                                                                                                                                                                                  |
| 2024-10-26T13:47:31.206Z | plugin:copilot:139422:19             | log   | \["New Vault QA chain with hybrid retriever created for entire vault"]                                                                                                                                                                |
| 2024-10-26T13:47:31.207Z | plugin:copilot:139423:19             | log   | \["Set chain:","vault_qa"]                                                                                                                                                                                                            |
| 2024-10-26T13:47:37.754Z | plugin:copilot:136493:19             | log   | \["Inserted document 3f6a64e9201f47c74b422a1faca7cc7e in VectorDB with path: console-log.Fairphone 4 5G.md"]                                                                                                                          |
| 2024-10-26T13:47:38.118Z | plugin:copilot:136493:19             | log   | \["Inserted document d1259d14d9104df5ed29e6c09930e671 in VectorDB with path: 3 Resources/Self-Improvement/Lost Connections.md"]                                                                                                       |
| 2024-10-26T13:47:39.381Z | plugin:copilot:136493:19             | log   | \["Inserted document 547c6c293afd97ceaae3d693518bcb9d in VectorDB with path: 3 Resources/Self-Improvement/The Science of Having a Great Conversation.md"]                                                                             |
| 2024-10-26T13:47:39.411Z | plugin:copilot:136493:19             | log   | \["Inserted document ad2ea9441caaf50b1b107bf498eb18b5 in VectorDB with path: 3 Resources/Self-Improvement/The Science of Having a Great Conversation.md"]                                                                             |
| 2024-10-26T13:47:39.419Z | plugin:copilot:136493:19             | log   | \["Inserted document 3aa774ed9f69b2e26cd80014c231a1d1 in VectorDB with path: 3 Resources/Self-Improvement/The Science of Having a Great Conversation.md"]                                                                             |                                                                                                     |
| 2024-10-26T13:47:49.126Z | plugin:copilot:136493:19             | log   | \["Inserted document a67e0a8e195777cabab6a163341a2382 in VectorDB with path: 3 Resources/Self-Improvement/The Danger of “What's Next”.md"]                                                                                            |
| 2024-10-26T13:47:49.562Z | http://localhost/app.js:1:486776     | warn  | \["Measure loop restarted more than 5 
|...|...|...|...|
| 2024-10-26T13:55:21.694Z | plugin:copilot:136493:19             | log   | \["Inserted document 8d2619f2c4fd8d80797aea4babb778d0 in VectorDB with path: 3 Resources/CompSci/How to Read and Do Proofs.md"]                                                                                                       |
| 2024-10-26T13:55:21.697Z | plugin:copilot:136493:19             | log   | \["Inserted document d3ab533cf2092f21e7c357d66fe8605f in VectorDB with path: 3 Resources/CompSci/How to Read and Do Proofs.md"]                                                                                                       |
| 2024-10-26T13:55:21.700Z | plugin:copilot:136493:19             | log   | \["Inserted document 705293d465439373bcab3a62317efb62 in VectorDB with path: 3 Resources/CompSci/How to Read and Do Proofs.md"]                                                                                                       |
| 2024-10-26T13:55:21.700Z | plugin:copilot:136497:15             | error | \["Error upserting document 335a2f48d23e147cfe29e2dffcd41406 in VectorDB:",{"code":"INVALID_INPUT_VECTOR"}]                                                                                                                           |
| 2024-10-26T13:55:21.701Z | plugin:copilot:136468:17             | error | \["Error storing vectors in VectorDB:",{"code":"INVALID_INPUT_VECTOR"}]                                                                                                                                                               |
| 2024-10-26T13:55:21.701Z | plugin:copilot:136497:15             | error | \["Error upserting document 9dc93c7aca1718f1fcf7cf2e8bd427de in VectorDB:",{"code":"INVALID_INPUT_VECTOR"}]                                                                                                                           |
| 2024-10-26T13:55:21.702Z | plugin:copilot:136468:17             | error | \["Error storing vectors in VectorDB:",{"code":"INVALID_INPUT_VECTOR"}]                                                                                                                                                               |
| 2024-10-26T13:55:21.702Z | plugin:copilot:136497:15             | error | \["Error upserting document fcb27255136c007ad82d10e1a910600c in VectorDB:",{"code":"INVALID_INPUT_VECTOR"}]                                                                                                                           |                                                                                                                        
|...|...|...|...|
| 2024-10-26T13:55:29.424Z | plugin:copilot:136497:15             | error | \["Error upserting document bce557900366f623b0e67cb9ed99805e in VectorDB:",{"code":"INVALID_INPUT_VECTOR"}]                                                                                                                           |
| 2024-10-26T13:55:29.425Z | plugin:copilot:136468:17             | error | \["Error storing vectors in VectorDB:",{"code":"INVALID_INPUT_VECTOR"}]                                                                                                                                                               |
| 2024-10-26T13:55:29.425Z | plugin:copilot:136497:15             | error | \["Error upserting document 125099cc1e00261d9dc0f65aa647576f in VectorDB:",{"code":"INVALID_INPUT_VECTOR"}]                                                                                                                           |
| 2024-10-26T13:55:29.426Z | plugin:copilot:136468:17             | error | \["Error storing vectors in VectorDB:",{"code":"INVALID_INPUT_VECTOR"}]                                                                                                                                                               |
| 2024-10-26T13:55:29.426Z | plugin:copilot:136497:15             | error | \["Error upserting document a5f7470ad708a5666edb2c74c21c80dc in VectorDB:",{"code":"INVALID_INPUT_VECTOR"}]                                                                                                                           |
| 2024-10-26T13:55:29.427Z | plugin:copilot:136468:17             | error | \["Error storing vectors in VectorDB:",{"code":"INVALID_INPUT_VECTOR"}]                                                                                                                                                               |
| 2024-10-26T13:55:29.427Z | plugin:copilot:136497:15             | error | \["Error upserting document 93f64c8a87db5924025274170d4ad50c in VectorDB:",{"code":"INVALID_INPUT_VECTOR"}]                                                                                                                           |
| 2024-10-26T13:55:29.427Z | plugin:copilot:136468:17             | error | \["Error storing vectors in VectorDB:",{"code":"INVALID_INPUT_VECTOR"}]                                                                                                                                                               |
| 2024-10-26T13:55:29.428Z | plugin:copilot:136497:15             | error | \["Error upserting document 39f98f77b588f3e6dfaffebb104c4c20 in VectorDB:",{"code":"INVALID_INPUT_VECTOR"}]                                                                                                                           |
| 2024-10-26T13:55:29.428Z | plugin:copilot:136468:17             | error | \["Error storing vectors in VectorDB:",{"code":"INVALID_INPUT_VECTOR"}]                                                                                                                                                               |
| 2024-10-26T13:55:29.539Z | plugin:copilot:136497:15             | error | \["Error upserting document 322785f21d971f100f7c403a06d8f6a5 in VectorDB:",{"code":"INVALID_INPUT_VECTOR"}]                                                                                                                           |
| 2024-10-26T13:55:29.539Z | plugin:copilot:136468:17             | error | \["Error storing vectors in VectorDB:",{"code":"INVALID_INPUT_VECTOR"}]                                                                                                                                                               |
| 2024-10-26T13:55:29.559Z | plugin:copilot:139422:19             | log   | \["New Vault QA chain with hybrid retriever created for entire vault"]                                                                                                                                                                |
| 2024-10-26T13:55:29.559Z | plugin:copilot:139423:19             | log   | \["Set chain:","vault_qa"]                                                                                                                                                                                                            |

**Comment by ivannin** [comment] 2024-11-01 11:12
I have the same problems: Obsidian crashes on my mobile phone while loading the Copilot plugin.

I am using:
- Samsung Note 20 5G (SM-N981N), RAM 8GB
- FolderSync for synchronization
- The size of the file `.obsidian/copilot-index-***.json` is over 250 GB

My temporary solution:

- I deleted the file `.obsidian/copilot-index-***.json` on my mobile device;
- I set a restriction for synchronization this file in FolderSync.

Now it's working.

**Comment by logancyang** [comment] 2024-11-01 20:41
@ivannin thanks for your data point! It looks like it's a hardware constraint: Mobile devices have less RAM.

Would it help to introduce ways to limit the size of the index, like a "inclusion" setting for indexing where you only index a small subset of the vault in order to have it work on smaller mobile devices.

Any suggestion is welcome!

**Comment by upnix** [comment] 2024-11-02 18:05
I sync my Obsidian vault to my phone in its entirety, so any pruning of what's indexed would impact my use on my computer as well.

The way I use Obsidian I wouldn't use an inclusion/exclusion setting. I would probably try to exclude syncing the .json index (via Syncthing) then not use the vault QA feature on my phone. So, as far as Copilot is concerned, I guess awareness of whether it's running on a computer or mobile would be nice, then have it gracefully realize that it doesn't have the vault QA index available and not try to create it on the phone.

A less graceful idea might be to have Copilot just not try to load the .json index until I select "Vault QA" - then I can just avoid using it on the phone and nothing else needs to change.


@logancyang - so is this a side effect of switching from PouchDB to Orama? Previous Copilot versions ran were ok, although I never tried using Vault QA.

**Comment by ivannin** [comment] 2024-11-04 11:41
As far as I understand, the `copilot-index-***.json` file is needed not only for Vault QA but also for finding similar notes. It might be useful to implement a plugin setting like "_Disable features based on vector storage_" and if this setting is turned ON, then do not load the `copilot-index-***.json`, do not display Vault QA, and hide the "Find Similar notes to active note" command.

**Comment by logancyang** [comment] 2024-11-05 22:47
In 2.7.1 I've shipped the new **Inclusion** filter as a temporary way around the crash. It takes precedence over exclusion, only things in Inclusion will be indexed, so you can manage the index size.

**Comment by logancyang** [comment] 2024-11-14 20:28
I added the option to disable index loading in setting in 2.7.2. When index is not loaded, only Chat mode is available, the other modes will not be selectable. 

I can use the disable feature correctly on my iOS devices. But someone reported this issue: #815 

If anyone can reproduce it pls comment on that issue.

**Closed by logancyang** 2024-11-14 20:28 UTC
Labels: question, mobile support

**Comment by TimS-ml** [comment] 2024-11-19 07:50
@logancyang My 8g RAM macbook + openAI text-embedding large also encountered the same issue. I got a pretty large vault (6k notes); however, the obsidian crashed at the end of indexing, and the `copilot-index-***.json` was only 3k.  Do you think we could embed multiple times (say in 100 notes per batch) and then merge everything together?
