### ISSUE TITLE
LangChain error: TypeError: Failed to fetch

### ISSUE THREAD

**Issue by dhammavipassi** [logancyang/obsidian-copilot#251] opened 2024-01-23 14:20 UTC
LangChain error: TypeError: Failed to fetch， how to solve this issue? Please!

**Comment by logancyang** [comment] 2024-01-23 19:28
@dhammavipassi can you show me the console log with debug on? Also describe how to reproduce, what model/mode and settings you have

**Comment by kennygokh** [comment] 2024-01-26 03:25
I having the same issue when I tried to use Ollama. Error in console as below. Please help.

_Access to fetch at 'http://127.0.0.1:11434/api/chat' from origin 'app://obsidian.md' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled._

_POST http://127.0.0.1:11434/api/chat net::ERR_FAILED
createOllamaStream @ plugin:copilot:70872
createOllamaChatStream @ plugin:copilot:70915
_streamResponseChunks @ plugin:copilot:71261
await in _streamResponseChunks (async)
_streamIterator @ plugin:copilot:69621
await in _streamIterator (async)
transform @ plugin:copilot:6021
await in transform (async)
transform @ plugin:copilot:6204
await in transform (async)
_streamIterator @ plugin:copilot:6506
await in _streamIterator (async)
pull @ plugin:copilot:5077
Promise.then (async)
IterableReadableStream @ plugin:copilot:4997
fromAsyncGenerator @ plugin:copilot:5075
stream @ plugin:copilot:5848
runChain @ plugin:copilot:73910
getAIResponse @ plugin:copilot:83019
handleSendMessage @ plugin:copilot:83110
handleKeyDown @ plugin:copilot:83125
callCallback2 @ plugin:copilot:45845
invokeGuardedCallbackDev @ plugin:copilot:45870
invokeGuardedCallback @ plugin:copilot:45904
invokeGuardedCallbackAndCatchFirstError @ plugin:copilot:45907
executeDispatch @ plugin:copilot:49187
processDispatchQueueItemsInOrder @ plugin:copilot:49207
processDispatchQueue @ plugin:copilot:49216
dispatchEventsForPlugins @ plugin:copilot:49224
eval @ plugin:copilot:49348
batchedUpdates$1 @ plugin:copilot:61080
batchedUpdates @ plugin:copilot:45750
dispatchEventForPluginEventSystem @ plugin:copilot:49347
dispatchEventWithEnableCapturePhaseSelectiveHydrationWithoutDiscreteEventReplay @ plugin:copilot:47649
dispatchEvent @ plugin:copilot:47643
dispatchDiscreteEvent @ plugin:copilot:47620
plugin:copilot:73971 TypeError: Failed to fetch
    at createOllamaStream (plugin:copilot:70872:26)
    at createOllamaStream.next (<anonymous>)
    at createOllamaChatStream (plugin:copilot:70915:10)
    at createOllamaChatStream.next (<anonymous>)
    at ChatOllama._streamResponseChunks (plugin:copilot:71261:24)
    at async ChatOllama._streamIterator (plugin:copilot:69621:26)
    at async ChatOllama.transform (plugin:copilot:6021:9)
    at async RunnableBinding.transform (plugin:copilot:6204:9)
    at async RunnableSequence._streamIterator (plugin:copilot:6506:28)
    at async Object.pull (plugin:copilot:5077:37)_

**Comment by logancyang** [comment] 2024-01-26 03:38
@kennygokh looks like you didn't use `OLLAMA_ORIGINS=app://obsidian.md* ollama serve` to start the server?

**Comment by kennygokh** [comment] 2024-01-26 03:59
I did run it before using it copilot. I also checked in browser that Ollama run ok in localhost.

**Comment by logancyang** [comment] 2024-01-26 04:05
@kennygokh I see that you didn't watch my release video 😅 This shows your address is already in use and your server is not started. You must exit the ollama app first (and clear any process that might run at that port).

If you are not comfortable with the terminal, I recommend using LM studio if possible.

**Comment by logancyang** [comment] 2024-01-28 20:36
Closing this now. Feel free to reopen if the issue persists.

**Closed by logancyang** 2024-01-28 20:36 UTC

**Comment by MinSomai** [comment] 2024-03-22 04:48
`set -gx OLLAMA_ORIGINS "app://obsidian.md*,chrome-extension://*"`

put this in config.fish for fish shell

**Comment by wpq3142** [comment] 2024-04-21 16:40
link:https://github.com/logancyang/obsidian-copilot/blob/master/local_copilot.md#start-ollama-server-for-obsidian

ollama serve启动服务器: 
       使用 启动本地服务器OLLAMA_ORIGINS=app://obsidian.md* ollama serve，这将允许 Obsidian 应用程序访问本地服务器而不会出现 CORS 问题。再次强调，OLLAMA_ORIGINS=app://obsidian.md*是必须的！
       
      Start Ollama server for Obsidian
Now, start the local server with OLLAMA_ORIGINS=app://obsidian.md* ollama serve, this will allow the Obsidian app to access the local server without CORS issues.

Again, OLLAMA_ORIGINS=app://obsidian.md* is required!

**Comment by wp-jackliu** [comment] 2024-04-25 06:18
> link:https://github.com/logancyang/obsidian-copilot/blob/master/local_copilot.md#start-ollama-server-for-obsidian
> 
> ollama serve启动服务器: 使用 启动本地服务器OLLAMA_ORIGINS=app://obsidian.md* ollama serve，这将允许 Obsidian 应用程序访问本地服务器而不会出现 CORS 问题。再次强调，OLLAMA_ORIGINS=app://obsidian.md*是必须的！
> 
> ```
>   Start Ollama server for Obsidian
> ```
> 
> Now, start the local server with OLLAMA_ORIGINS=app://obsidian.md* ollama serve, this will allow the Obsidian app to access the local server without CORS issues.
> 
> Again, OLLAMA_ORIGINS=app://obsidian.md* is required!

base on the info, also have CORS issues ...

**Comment by wp-jackliu** [comment] 2024-04-25 06:20
<img width="1457" alt="image" src="https://github.com/logancyang/obsidian-copilot/assets/3220935/7868b8ae-1847-4c1b-8203-c3640399e317">

**Comment by KarlLightman** [comment] 2024-06-10 15:14
@kennygokh I dont know if u already solved the problem, if not, you can try command: ollama pull nomic-embed-text
