### ISSUE TITLE
[BUG] Ollama service dosent work after update

### ISSUE THREAD

**Issue by wwjCMP** [logancyang/obsidian-copilot#579] opened 2024-09-01 14:51 UTC
My Ollama service is on another local linux computer

**Comment by logancyang** [comment] 2024-09-01 18:46
What do the logs say, did you enable CORS?

**Comment by williamlwclwc** [comment] 2024-09-01 21:54
I had a similar issue, I got 404 on Ollama API calls. Not sure if I did anything wrong since I noticed my previous Ollama config is gone after latest update

```
OLLAMA_ORIGINS=app://obsidian.md* ollama serve
2024/09/01 13:31:03 routes.go:1125: INFO server config env="map[OLLAMA_DEBUG:false OLLAMA_FLASH_ATTENTION:false OLLAMA_HOST:http://127.0.0.1:11434 OLLAMA_KEEP_ALIVE:5m0s OLLAMA_LLM_LIBRARY: OLLAMA_MAX_LOADED_MODELS:0 OLLAMA_MAX_QUEUE:512 OLLAMA_MODELS:/Users/williamliu/.ollama/models OLLAMA_NOHISTORY:false OLLAMA_NOPRUNE:false OLLAMA_NUM_PARALLEL:0 OLLAMA_ORIGINS:[app://obsidian.md* http://localhost https://localhost http://localhost:* https://localhost:* http://127.0.0.1 https://127.0.0.1 http://127.0.0.1:* https://127.0.0.1:* http://0.0.0.0 https://0.0.0.0 http://0.0.0.0:* https://0.0.0.0:* app://* file://* tauri://*] OLLAMA_RUNNERS_DIR: OLLAMA_SCHED_SPREAD:false OLLAMA_TMPDIR:]"
time=2024-09-01T13:31:03.430-07:00 level=INFO source=images.go:753 msg="total blobs: 9"
time=2024-09-01T13:31:03.432-07:00 level=INFO source=images.go:760 msg="total unused blobs removed: 0"
time=2024-09-01T13:31:03.432-07:00 level=INFO source=routes.go:1172 msg="Listening on 127.0.0.1:11434 (version 0.3.9)"
time=2024-09-01T13:31:03.433-07:00 level=INFO source=payload.go:30 msg="extracting embedded files" dir=/var/folders/hm/h00h5px10kz3lgg5jpt41h_r0000gn/T/ollama396951871/runners
time=2024-09-01T13:31:03.469-07:00 level=INFO source=payload.go:44 msg="Dynamic LLM libraries [metal]"
time=2024-09-01T13:31:03.511-07:00 level=INFO source=types.go:107 msg="inference compute" id=0 library=metal variant="" compute="" driver=0.0 name="" total="21.3 GiB" available="21.3 GiB"
[GIN] 2024/09/01 - 13:31:10 | 200 |      60.584µs |       127.0.0.1 | GET      "/api/version"
[GIN] 2024/09/01 - 13:31:10 | 200 |    5.414416ms |       127.0.0.1 | GET      "/api/tags"
[GIN] 2024/09/01 - 13:31:10 | 200 |    1.543833ms |       127.0.0.1 | GET      "/api/tags"
[GIN] 2024/09/01 - 13:31:10 | 200 |      870.75µs |       127.0.0.1 | GET      "/api/tags"
[GIN] 2024/09/01 - 13:31:10 | 200 |    4.747875ms |       127.0.0.1 | GET      "/api/tags"
[GIN] 2024/09/01 - 13:31:10 | 200 |    7.364958ms |       127.0.0.1 | GET      "/api/tags"
[GIN] 2024/09/01 - 13:31:10 | 200 |    1.082166ms |       127.0.0.1 | GET      "/api/tags"
[GIN] 2024/09/01 - 13:31:10 | 200 |   28.872125ms |       127.0.0.1 | POST     "/api/show"
[GIN] 2024/09/01 - 13:31:46 | 404 |      619.75µs |       127.0.0.1 | POST     "/v1/chat/completions"
[GIN] 2024/09/01 - 13:37:13 | 404 |     676.292µs |       127.0.0.1 | POST     "/v1/chat/completions"
[GIN] 2024/09/01 - 13:37:13 | 404 |     257.792µs |       127.0.0.1 | POST     "/v1/chat/completions"
[GIN] 2024/09/01 - 13:37:14 | 404 |    5.028958ms |       127.0.0.1 | POST     "/v1/chat/completions"
[GIN] 2024/09/01 - 13:37:16 | 404 |     380.958µs |       127.0.0.1 | POST     "/v1/chat/completions"
[GIN] 2024/09/01 - 13:37:17 | 404 |     263.625µs |       127.0.0.1 | POST     "/v1/chat/completions"
[GIN] 2024/09/01 - 13:37:18 | 404 |     866.792µs |       127.0.0.1 | POST     "/v1/chat/completions"
[GIN] 2024/09/01 - 13:37:20 | 404 |      425.25µs |       127.0.0.1 | POST     "/v1/chat/completions"
[GIN] 2024/09/01 - 13:37:21 | 404 |     233.125µs |       127.0.0.1 | POST     "/v1/chat/completions"
[GIN] 2024/09/01 - 13:37:22 | 404 |     245.417µs |       127.0.0.1 | POST     "/v1/chat/completions"
[GIN] 2024/09/01 - 13:37:27 | 404 |     227.666µs |       127.0.0.1 | POST     "/v1/chat/completions"
[GIN] 2024/09/01 - 13:37:27 | 404 |     330.542µs |       127.0.0.1 | POST     "/v1/chat/completions"
[GIN] 2024/09/01 - 13:37:28 | 404 |     266.125µs |       127.0.0.1 | POST     "/v1/chat/completions"
```

**Comment by logancyang** [comment] 2024-09-02 00:42
@williamlwclwc 404 usually means you didn't `ollama pull` the model name you specified. Right now, you add a Custom Model with the exact name of the model, it must be present in Ollama.

**Comment by teddyzxcv** [comment] 2024-09-02 04:13
@williamlwclwc Try to run `ollama ls` and see is the used model exist in Ollama

**Comment by williamlwclwc** [comment] 2024-09-02 05:32
Yeah I should use the model name instead of `ollama`, it works now, thank you

**Comment by jsrdcht** [comment] 2024-09-02 06:07
> What do the logs say, did you enable CORS?
> 
> In your case, you probably need to set the base URL correctly to access that linux machine on your local network. So instead of using `ollama` as model provider, you need `openai-format` instead.

When using openai-format, it always prompts for an API key. However, with the previous version using the ollama (cloud deployment) model, there was no need for an API key, and the ollama model also does not have an API key.

**Comment by logancyang** [comment] 2024-09-02 06:16
@jsrdcht i just released 2.6.1, can you try if this fixed your issue

**Comment by jsrdcht** [comment] 2024-09-02 06:30
> @jsrdcht i just released 2.6.1, can you try if this fixed your issue

I‘m using 2.6.1

**Comment by logancyang** [comment] 2024-09-02 06:44
@jsrdcht 2.6.1 fills an placeholder api key for openai-format model without an api key set. Can you refresh the plugin/delete re-add model and try again?

**Comment by jsrdcht** [comment] 2024-09-02 07:18
> @jsrdcht 2.6.1 fills an placeholder api key for openai-format model without an api key set. Can you refresh the plugin/delete re-add model and try again?

![image](https://github.com/user-attachments/assets/c7047291-f9a1-4168-af4d-9d0acd7795c3)

**Comment by wwjCMP** [comment] 2024-09-02 14:44
![image](https://github.com/user-attachments/assets/86ec8e6c-a730-41bc-8d99-8d3aa30bc647)
maybe we need this for remote service

**Comment by logancyang** [comment] 2024-09-02 18:06
@wwjCMP @jsrdcht Ah sorry i found the issue, will be fixed with #585

**Comment by wwjCMP** [comment] 2024-09-04 07:10
> @wwjCMP @jsrdcht Ah sorry i found the issue, will be fixed with #585. In the meantime, you can set a random string as API key.

![image](https://github.com/user-attachments/assets/339354e5-1e06-4db5-b818-aa78dc6e0b32)

**Comment by covercash2** [comment] 2024-09-05 01:47
+1
Ollama was working perfectly until i updated :/

**Comment by covercash2** [comment] 2024-09-05 01:49
is the Ollama API not supported anymore?

**Comment by logancyang** [comment] 2024-09-05 04:08
Don't you guys watch my release video? 😢

404 means you have not pulled the ollama model

**Comment by wwjCMP** [comment] 2024-09-05 04:24
> Don't you guys watch my release video? 😢
> 
> 404 means you have not pulled the ollama model

I don't think this is the wrong reason, I use a third party compatible way to successfully use ollama

**Comment by logancyang** [comment] 2024-09-05 04:43
@wwjCMP In your case, the correct way is to use 3rd party openai-format provider, not Ollama, since you are not using localhost. This is by design. Ollama doesn't need a separate override anymore.

**Comment by logancyang** [comment] 2024-09-05 04:52
@wwjCMP 2.6.2 is live. It should fix your issue.

**Closed** 2024-09-05 04:53 UTC
Labels: question
