### ISSUE TITLE
For vector embedding of cohereAI, it reports an error

### ISSUE THREAD

**Issue by zonszer** [logancyang/obsidian-copilot#114] opened 2023-07-20 05:00 UTC
Hi, thanks for the plugin!

In the latest version (2.3.6) when using cohere AI API key for vector embedding, it reports an error:
![image|500](https://github.com/logancyang/obsidian-copilot/assets/69456052/f52492a7-b787-4467-b319-3b49c1d5fcde)

But when I changed to huggingface API key it works well.  
Still not known why this problem occurs, could anyone provide some suggestions?

**Comment by logancyang** [comment] 2023-07-20 21:48
Hmm, I just tried and cohereAI embedding is working for me. So you don't even see the "Vector store created successfully" message, right?

This is what GPT4 says, so I suspect Cohere is returning some HTML 404 page because of wrong credentials. Is your API key correct? I wonder if anybody else is seeing this issue as well.
<img width="929" alt="Screenshot 2023-07-20 at 2 45 37 PM" src="https://github.com/logancyang/obsidian-copilot/assets/4860545/00e38217-79a6-46be-9516-1cbf7a8d639f">

**Comment by zonszer** [comment] 2023-07-21 03:38
Thank you for your prompt response! I have recently checked and tested my cohere API key. Based on my evaluation, the cohere API key in obsidian-copilot appears to be correct as it successfully ran in other instances, resulting in usage billing. So, I am still unsure about the cause of this particular issue. 
![image](https://github.com/logancyang/obsidian-copilot/assets/69456052/355c9f17-0ee6-4e2e-8602-ab635ae776db)

Anyway, I sincerely appreciate your assistance! Perhaps, when I have some free time, I should examine the return value of the post to gain further information.

**Comment by zonszer** [comment] 2023-07-21 03:40
Thank you for your prompt response! I have recently checked and tested my cohere API key. Based on my evaluation, the cohere API key in obsidian-copilot appears to be correct as it successfully ran in other instances, resulting in usage billing. So, I am still unsure about the cause of this particular issue.

![image](https://github.com/logancyang/obsidian-copilot/assets/69456052/355c9f17-0ee6-4e2e-8602-ab635ae776db) 
Anyway, I sincerely appreciate your assistance! Perhaps, when I have some free time, I should examine the return value of the post to gain further information.

**Comment by ZHN202** [comment] 2023-10-19 04:22
I'm having the same problem. @logancyang It should be a network problem. @zonszer 
![image](https://github.com/logancyang/obsidian-copilot/assets/76200017/0aafa6fb-2b22-4d46-8c4a-36d6d67dcd15)
I called cohere's python api to test it and can reproduce the same problem when closing the web proxy. When I turn on the web proxy, I can use the python api without problems, but the problem still occurs on obsidian. I don't have a solution yet. Maybe it's a problem with the typescript api. When the official implementation of the interface comes out there may be no problem at all!

**Comment by 22rikard** [comment] 2023-10-19 08:34
same issue,it return statusCode 502 bad gate,it seem like it had been blocked me,although i was using gobal mode in CLASH. 
i fix it by turn on the 'TUN MODE' in CLASH

**Comment by ZHN202** [comment] 2023-10-19 08:53
> same issue,it return statusCode 502 bad gateway,it seem like it had been blocked me,although i was using gobal mode in CLASH. i fix it by turn on the 'TUN MODE' in CLASH

I opened the TUN MODE and it still doesn't work, do I need to change any configuration in CLASH?

**Comment by ZHN202** [comment] 2023-10-19 09:08
> same issue,it return statusCode 502 bad gateway,it seem like it had been blocked me,although i was using gobal mode in CLASH. i fix it by turn on the 'TUN MODE' in CLASH
Thank you. Problem solved.

**Closed** 2024-08-09 21:56 UTC
