### ISSUE TITLE
Question regarding folder constraints in Vault QA mode

### ISSUE THREAD

**Issue by AW2307** [logancyang/obsidian-copilot#823] opened 2024-11-16 13:01 UTC
Hi,

I'm attempting to use folder constraints in vault qa mode. However, the response always contains notes from across the vault.

In chat mode, the folder constraints work as intended.

Could you please take a look?

**Comment by logancyang** [comment] 2024-11-16 19:30
What do you mean by folder constraint? 

- Is it `{folder}` in custom prompt? If yes, this is by design. `{folder}` is just a way to pass the things in that folder to the input, the output is still from vault search.
- Is it "exclusion" or "inclusion" filter? If yes, you have to clear your copilot index first because any "refresh index" does not remove previously indexed files.

**Comment by AW2307** [comment] 2024-11-16 21:33
> Is it {folder} in custom prompt? If yes, this is by design. {folder} is just a way to pass the things in that folder to the input, the output is still from vault search.

Yes, that's it.

May I ask why by design the folder constraint is not available in vault qa mode? Since it seems to be working in chat mode.

Basically I would like to accomplish two things:
- use only notes from specific folder/s as context 
- see the specific notes that were used to generate a response to my prompt 

Is there any way to accomplish this?

Thx by the way for a really useful plugin.

**Comment by logancyang** [comment] 2024-11-16 21:51
@AW2307 I see. `Vault QA (basic)` is a mode that searches the entire indexed context - the whole vault by default. `{folder}` is just a template that passes whatever notes into your input, so Vault QA mode uses your extremely long input to search the entire vault.

To achieve your goal, you need the `inclusion` filter and only index those folders you want as context. Keep in mind that you have to run Copilot command "Clear vector store" first, set the inclusion filter correctly, and trigger a new round of indexing. Any of your previous index will be overwritten, so beware.

There's a "Project-based context" FR in the open issues and that will avoid the need to reindex and overwrite the whole index.

**Comment by AW2307** [comment] 2024-11-16 22:06
Thanks for explaining.

The context in most of the folders I'd like to use is too large to use it in chat mode, so this leaves only the reindexing option.

Project-based context would be super useful! I strongly support that feature request

**Comment by logancyang** [comment] 2024-12-20 00:31
This should be addressed by #375

**Closed by logancyang** 2024-12-20 00:31 UTC
Labels: question
