### ISSUE TITLE
Re-indexing on every restart of Obsidian: RangeError: Invalid string length at JSON.stringify

### ISSUE THREAD

**Issue by nieleyde** [logancyang/obsidian-copilot#834] opened 2024-11-21 02:21 UTC
Copilot version: 2.7.2

**Describe how to reproduce**
I have set Copilot auto-index vault policy to NEVER.
I am using mxbai-embed-large embedding model via ollama.
I trigger command to re-index.  I have about 9K+ files processed successfully.
I am able to successfully run Vault QA on my documents.
I can add/edit new documents.
I initiate the refresh index command, and the new documents get indexed correctly.
Once again, I am able successfully run Vault QA on my documents.
However when I shutdown Obsidian and restart, Vault QA doesn't work.
I initiate the refresh index command, and all the documents (9k+) are reindexed.

**Expected behavior**
I would have expected the vector store to persist between Obsidian sessions.  When I restart Obsidian, I shouldn't need to re-index the entire vault.
I am pretty sure this was the behavior with prior versions of copilot.

**Comment by logancyang** [comment] 2024-11-21 07:14
If the "refresh index" command triggers a complete re-index, it could mean 2 things:

1. Your embedding model has changed in your setting, so a complete reindex is needed for the new embedding model
2. The previous index was not loaded correctly

For 1, Copilot checks whether the embedding model is the same as previous by comparing the model name and vector dimension of the current model against the existing one in the index. So any change on the Ollama side, e.g. model file change could trigger this.

For 2, there can be a few possibilities, either contamination of index file, RAM issue, or something else we haven't seen before.

Is this a consistent issue every time you reopen Obsidian? Any dev console messages will be helpful.

**Comment by logancyang** [comment] 2024-11-21 07:20
I can't reproduce on my new feature branch 2.7.3, it should be fixed in the next release.

**Comment by logancyang** [comment] 2024-11-26 00:05
@nieleyde My vault with ~6k notes is working as expected now, can't reproduce this at the moment. Not sure what's causing this error in your vault 🤔

If others see this please chime in! Need more signal to understand this one.

**Comment by nieleyde** [comment] 2024-11-26 04:19
> @nieleyde My vault with ~6k notes is working as expected now, can't reproduce this at the moment. It could be that your vault has some really really long notes. I may need to implement partitioning for the index file for this.
> 
> In the meantime, could you test by adding some "exclusion" filters in your Copilot setting to leave the less important stuff out. If that works then we know that the offender is in the excluded stuff.
> 
> If others see this error please chime in!

I looked at my vault.  I found one ridiculously large .md file (4+MB).  I removed it, and the error seems to go away.

**Comment by logancyang** [comment] 2024-12-20 00:27
Please update to 2.7.10 and increase the number of partitions under QA settings, it should fix any issue around large vaults!

**Closed by logancyang** 2024-12-20 00:27 UTC
Labels: bug, milestone
