### ISSUE TITLE
'Index not loaded'

### ISSUE THREAD

**Issue by chriswhite5918** [logancyang/obsidian-copilot#837] opened 2024-11-22 10:12 UTC
- [x] Disable all other plugins besides Copilot **(required)**
- [x] Screenshot of note + Copilot chat pane + dev console added **(required)**

Copilot version: 2.7.2

**Describe how to reproduce**

I’m using the desktop version. After installing the plugin, configuring the API, and restarting the plugin as instructed, I found that QA mode isn’t working, with the message 'Index not loaded.' Restarting the plugin didn’t help either. I tried forcing the index using a shortcut, but it showed the message 'Indexing is disabled on mobile devices.'

I then created a new empty vault and only installed your plugin, but the result was the same. 

**Expected behavior**

The expected outcome should be that indexing works normally. Even if there’s an issue with the API, it should indicate an API-related problem rather than saying 'Indexing is disabled on mobile devices.

**Screenshots**
<img width="700" alt="Obsidian_soOE1ipKkR" src="https://github.com/user-attachments/assets/7b85b8d2-c351-4139-a934-090ddf23a545">

<img width="506" alt="Obsidian_3cKrDo2nQe" src="https://github.com/user-attachments/assets/aede5cf0-a39d-4095-ab0e-8a8c0f44d6f0">

<img width="828" alt="Obsidian_4VgcUryLxb" src="https://github.com/user-attachments/assets/6efb5c0f-9530-4274-be88-1fe00e99e54b">

**Comment by logancyang** [comment] 2024-11-22 19:15
#825 fix was merged.

**Comment by chriswhite5918** [comment] 2024-11-23 03:11
> #825 was merged. Should be fixed in the next release v2.7.3.
> 
> In the meantime the solution is to refresh with the dev console open.
I updated to version 2.7.3, but the same issue persists. Then I tried shortcuts like Ctrl+R and Ctrl+Shift+R to refresh with dev console open, but the issue still remains after refreshing.
<img width="709" alt="Obsidian_pRCc08V0px" src="https://github.com/user-attachments/assets/5d0bc24c-2a16-44a0-9040-7d54e4eb5b2e">

**Comment by logancyang** [comment] 2024-11-23 03:51
@chriswhite5918  Could you turn on debug mode as the issue template suggests? The debug messages might help. For now I can't reproduce this behavior on my end.

What's your OS and what embedding model do you have?

**Comment by chriswhite5918** [comment] 2024-11-26 02:46
> @chriswhite5918 Could you turn on debug mode as the issue template suggests? The debug messages might help. For now I can't reproduce this behavior on my end.
> 
> What's your OS and what embedding model do you have? 

OS: windows
embedding: text-embedding-3-small
Looks like the latest version fixed the 'Index not loaded' bug. It seems my model is having issues with this plugin, though it's working fine on Dify. I might need to spend some time figuring out what's going on.

**Comment by logancyang** [comment] 2024-11-26 03:03
@chriswhite5918 what model are you using?

**Comment by onaimad** [comment] 2024-11-26 09:27
I have the same issue, even on latest version, when using a local model.
It seems API key is mandatory when using 3rd party provider of local model in QA mode. The exact same model works perfectly when added (w/out API key) in chat mode.
OS: Mac Os 15.1
local model: llama3.2-3b-instruct
url: http://localhost:1337 (Jan.ai)

Monitoring the log of the local model server, there are no requests being made if API key is not provided (in QA mode), whereas if using a random key (any string given it's not necessary) the request is sent correctly to the server but it obviously get rejected as the API key parameter is not needed.

**Closed** 2024-12-09 20:54 UTC
Labels: bug
