### ISSUE TITLE
Increasing token limit breaks co-pilot

### ISSUE THREAD

**Issue by noahevers97** [logancyang/obsidian-copilot#1] opened 2023-04-25 11:01 UTC
When increasing the token limit of co-pilot above 1000, I do not get any response from chat-gpt, also not after a restart. Setting the token limit <1000 fixes the issue again.

**Comment by logancyang** [comment] 2023-04-25 18:20
Thanks for reporting the issue @noahevers97! Hmm, I can't seem to reproduce this, I tried 2000 for both gpt3.5 and gpt4, they are working fine for me. Do you see any console errors?

**Comment by spiritualgeek** [comment] 2023-05-06 15:13
I had mine set to 5000 and had to go back to 1000 otherwise it wouldn't work, complaining about credentials/API Key. I love this concept of interacting with GPT. Thanks for the plugin!

**Comment by logancyang** [comment] 2023-05-06 15:47
> I had mine set to 5000 and had to go back to 1000 otherwise it wouldn't work, complaining about credentials/API Key. I love this concept of interacting with GPT. Thanks for the plugin!

Thanks for trying it out! Sorry about the confusing error message, that API key complaint is currently covering all OpenAI errors. If you open your console you will see the true error message which is quite long. I suspect the 5000 token limit is over what is allowed for that model you are using. Feel free to copy and paste the console error message here, I can take a look.

I will add better error messages soon.

**Comment by spiritualgeek** [comment] 2023-05-07 09:20
```
api.openai.com/v1/chat/completions:1     Failed to load resource: the server responded with a status of 400 ()
plugin:copilot:37818 Error in streamManager.streamSSE: CustomEvent
getAIResponse @ plugin:copilot:37818
```

**Comment by logancyang** [comment] 2023-05-10 23:34
Basically the issue is that the model you picked does not support token limit as big as 5000

I added better error message like this, hope it helps

<img width="883" alt="Screenshot 2023-05-10 at 4 27 36 PM" src="https://github.com/logancyang/obsidian-copilot/assets/4860545/c5c57d0d-f8fc-4395-829e-9a2c52b425df">

In the meantime, please keep the OpenAI limitations in mind. You can find the API token limits in their docs: https://platform.openai.com/docs/models/overview

I'm planning to support unlimited context in the near future, please stay tuned!

**Comment by logancyang** [comment] 2023-05-12 18:42
Closing this one for now, please open a new issue with the new error messages if you still encounter problems.

**Closed by logancyang** 2023-05-12 18:42 UTC

**Comment by spiritualgeek** [comment] 2023-05-13 10:48
Thank you for the info. Appreciated
