### ISSUE TITLE
Options validation issue: temperature accepts any integer and no decimals

### ISSUE THREAD

**Issue by rbellamy** [logancyang/obsidian-copilot#37] opened 2023-05-28 00:41 UTC
I installed the plugin and went to set the temperature.

Found that it accepts any integer (positive or negative), but errors with a decimal (e.g. `0.7`).

Attached screenshots. The validation error is for `0.2`, which is my desired temperature.

![Selection_050](https://github.com/logancyang/obsidian-copilot/assets/94763/660048fc-0410-49eb-a60e-1bac71ca4879)
![Selection_051](https://github.com/logancyang/obsidian-copilot/assets/94763/388ffe51-4b2e-4b2b-bf0b-efe0a4e9e4fc)
![Selection_052](https://github.com/logancyang/obsidian-copilot/assets/94763/19c7a7a9-0e7e-43fc-bfc8-8c9897118777)
![Selection_053](https://github.com/logancyang/obsidian-copilot/assets/94763/5cc98577-eede-4f46-9714-26256b6253fc)

**Comment by logancyang** [comment] 2023-05-28 22:40
Hi @rbellamy , thanks for reporting. However I can't reproduce this. It's behaving correctly for me

![image](https://github.com/logancyang/obsidian-copilot/assets/4860545/a8abc0f2-cb5f-489f-8428-52815b35b3a1)

![image](https://github.com/logancyang/obsidian-copilot/assets/4860545/281d9fae-8f90-47c0-bb3c-f75f671dfb04)

And you should be getting an error from OpenAI if you set it to be something invalid like `-7`.
![image](https://github.com/logancyang/obsidian-copilot/assets/4860545/7d5066c3-73f3-46a5-85fc-18285073c962)

I see your PR, but is there a `decimal` type on HTML form input? Can you give me a reference for that? `number` is working correctly for me.

**Comment by rbellamy** [comment] 2023-05-28 23:31
I closed the PR - you're correct. It wasn't valid.

My problem persists. I'm on Linux.

Here's what the console looks like after I've cleared it and start changing the settings.

![Selection_055](https://github.com/logancyang/obsidian-copilot/assets/94763/f81fd01e-a3f2-4e77-abf2-9bf7f84c3fa7)

And here's what the cell looks like when I enter `0.2`.

![Selection_057](https://github.com/logancyang/obsidian-copilot/assets/94763/23c5fca4-b1a4-4cce-b4dd-5073e57e6e88)

**Comment by logancyang** [comment] 2023-05-28 23:58
I see. Could it be your locale setting? Anyways, here's what I'm gonna do, I'm gonna make it a slider with an input box where the input box will also have a `step` attribute with min step `0.01`. That way if the input box doesn't work at least the slider will work.

**Comment by rbellamy** [comment] 2023-05-29 00:56
One more tidbit... I can trigger the behavior in the other three input boxes by entering decimals.

![Selection_059](https://github.com/logancyang/obsidian-copilot/assets/94763/669e657d-df6c-4f81-95a8-cd938e606735)

**Comment by logancyang** [comment] 2023-05-29 03:37
> One more tidbit... I can trigger the behavior in the other three input boxes by entering decimals.
> 
> ![Selection_059](https://user-images.githubusercontent.com/94763/241601329-669e657d-df6c-4f81-95a8-cd938e606735.png)

Probably a good idea to have sliders for all these then.

**Comment by logancyang** [comment] 2023-05-30 14:22
The sliders are implemented. Let me know if there's still problems. Closing for now.

**Closed by logancyang** 2023-05-30 14:22 UTC
