### ISSUE TITLE
Stop Generating button doesn't work

### ISSUE THREAD

**Issue by RobertoGongora** [logancyang/obsidian-copilot#54] opened 2023-06-02 16:24 UTC
Running Obsidian 1.3.5, plugin version 2.2.0, using GPT-4 model.

Steps to reproduce:

- Open Copilot sidebar
- Ask anything
- Click Stop Generating

Expected Result:

- The message stream stops

Actual result:

- The message stream keeps generating

Video:

https://github.com/logancyang/obsidian-copilot/assets/1845147/cb8db9a7-ef1e-4c8b-ac93-2649130f6dec

**Comment by logancyang** [comment] 2023-06-02 17:37
I see, it's because you are in `QA: Active Note` mode, and it currently doesn't support stop streaming. I will look into whether this chain supports the cancel feature in Langchain.

For non-QA use cases, don't forget to switch back to `Conversation` mode. If you stay in QA mode, it will send every query of yours to the embedding provider to get the embedding for search, and if you use OpenAI, it means $$. Plus there's also a chance that it won't answer your question because it's not relevant to its context.

**Comment by logancyang** [comment] 2023-06-06 03:55
Asked in langchainjs https://github.com/hwchase17/langchainjs/issues/1553

**Comment by logancyang** [comment] 2023-06-17 21:44
LangchainJS just merged a fix, will try again when they push a new release.

**Comment by Neuro-Dynamics** [comment] 2023-07-12 01:07
Still not working properly. This time when you press the Stop button, it stops the current streaming chat box, but immediately opens a new one with a copy of the previous text and continues to stream on the new chat box.

**Comment by logancyang** [comment] 2023-07-12 06:15
@Neuro-Dynamics hmm yes I can reproduce. This was working when I tested before the release, strange. Will look further.

**Comment by logancyang** [comment] 2024-01-25 00:08
Sorry about the late fix, this is finally fixed after migrating to LCEL in v2.4.12

**Closed by logancyang** 2024-01-25 00:08 UTC
Labels: bug
